server:
  port: 8090

test:
  uri: http://localhost:8101

spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, lyu
      routes:
        # 定义了一个名为"api_route"的路由规则,该规则将匹配以"/api/"开头的路径,例如"/api/user",
        # 并将这些请求转发到"http://localhost:8201"这个目标地址
        - id: api_route
          uri: http://localhost:8201
          predicates:
            - Path=/api/**
  redis:
    host: localhost
    port: 6379
    password: 123456  # 如果有密码
    timeout: 5000
    database: 0

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

# 以下配置指定了应用的名称、使用的协议（Dubbo）、注册中心的类型（Nacos）和地址
dubbo:
  application:
    # 设置应用的名称
    name: dubbo-springboot-demo-consumer
    qos-port: 33333
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    address: nacos://localhost:8848?username=nacos&password=nacos
    parameters.register-consumer-url: true
